import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button } from '../components/atoms/button';
import { FILTER, Filter } from '../consts';
import { Todo } from '../types/todo';




export default function Home() {
    const [text, setText] = useState('');
    const [todos, setTodos] = useState<Todo[]>([]);
    const [filter, setFilter] = useState<Filter>(FILTER.ALL);

    const handleOnSubmit = () => {
        if (!text) return

        const newTodo: Todo = {
            value: text,
            id: new Date().getTime(),
            checked: false,
            removed: false,
        };

        setTodos([newTodo, ...todos]);
        setText('');
    };

    const handleOnChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setText(e.target.value);
    };

    const handleOnEdit = (id: number, value: string) => {
        const newTodos = todos.map((todo) => {
            if (todo.id === id) {
                todo.value = value;
            }
            return todo;
        });

        setTodos(newTodos);
    };

    const handleOnChecked = (id: number) => {
        const newTodos = todos.map((todo) => {
            if (todo.id === id) {
                todo.checked = !todo.checked;
            }
            return todo;
        });

        setTodos(newTodos);
    };

    const handleOnRemove = (id: number) => {
        const newTodos = todos.map((todo) => {
            if (todo.id === id) {
                todo.removed = !todo.removed;
            }
            return todo;
        });

        setTodos(newTodos);
    };

    const filteredTodos = todos.filter((todo) => {
        switch (filter) {
            case FILTER.ALL:
                return !todo.removed;
            case FILTER.CHECKED:
                return todo.checked && !todo.removed;
            case FILTER.UNCHECKED:
                return !todo.checked && !todo.removed;
            case FILTER.REMOVED:
                return todo.removed;
            default:
                return todo;
        }
    });

    const handleOnEmpty = () => {
        const newTodos = todos.filter((todo) => !todo.removed);
        setTodos(newTodos);
    };


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>ToDo App</h1>
                <div>
                    <select defaultValue={FILTER.ALL}
                        onChange={(e) => setFilter(e.target.value as Filter)}
                    >
                        <option value={FILTER.ALL}>すべてのタスク</option>
                        <option value={FILTER.CHECKED}>完了したタスク</option>
                        <option value={FILTER.UNCHECKED}>現在のタスク</option>
                        <option value={FILTER.REMOVED}>ゴミ箱</option>
                    </select>
                    {filter === FILTER.REMOVED ? (
                        <button
                            onClick={(handleOnEmpty)}
                            disabled={todos.filter((todo) => todo.removed).length === 0}
                        >
                            ゴミ箱を空にする
                        </button>
                    ) : (
                        <form
                            onSubmit={(e) => {
                                e.preventDefault();
                                handleOnSubmit();
                            }}
                        >
                            <input
                                type="text"
                                disabled={filter === FILTER.CHECKED}
                                value={text}
                                onChange={(e) => handleOnChange(e)}
                            />
                            <input
                                type="submit"
                                disabled={filter === FILTER.CHECKED}
                                value="追加"
                                onSubmit={handleOnSubmit}
                            />
                        </form>
                    )}
                    <ul>
                        {filteredTodos.map(({ id, checked, removed, value }) => {
                            return (
                                <li key={id}>
                                    <input
                                        type="checkbox"
                                        disabled={removed}
                                        checked={checked}
                                        onChange={() => handleOnChecked(id)}
                                    />
                                    <input
                                        type="text"
                                        disabled={checked || removed}
                                        value={value}
                                        onChange={(e) => handleOnEdit(id, e.target.value)}
                                    />
                                    <Button text={removed ? '復元' : '削除'} onClick={() => handleOnRemove(id)} />
                                </li>
                            );
                        })}
                    </ul>
                </div>
            </main >

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div >
    )
}
