import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

type Todo = {
    value: string;
}

export default function Home() {
    const [text, setText] = useState('');
    const [todos, setTodos] = useState<Todo[]>([]);

    const handleOnSubmit = () => {
        if (!text) return

        const newTodo: Todo = {
            value: text,
        };

        setTodos([newTodo, ...todos]);
        setText('');
    };


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>ToDo App</h1>
                <div>
                    <form
                        onSubmit={(e) => {
                            e.preventDefault();
                            handleOnSubmit();
                        }}
                    >
                        <input type="text"
                            value={text}
                            onChange={(e) => setText(e.target.value)}
                        />
                        <input
                            type="submit"
                            value="追加"
                            onSubmit={handleOnSubmit}
                        />
                    </form>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}
